"""A cinematic of a game environment whose every texture was painted by Texel.

Nothing here is a stock material. Each texture is generated by driving
core.raster / core.canvas - the same code the paint operator calls - written
into a bpy Image, and applied with nearest-neighbour filtering so texels stay
square. If the add-on could not paint, this film could not exist.

  blender --background --factory-startup --python cinematic.py
"""
import math
import os
import subprocess
import sys
import time

import bpy

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from core import raster as R
from core.canvas import Canvas

OUT = os.path.join(HERE, "promo", "cinematic")
FRAMES = os.path.join(OUT, "frames")
os.makedirs(FRAMES, exist_ok=True)
for f in os.listdir(FRAMES):
    os.remove(os.path.join(FRAMES, f))

W = H = 1280, 720
RES = (1280, 720)
SAMPLES = 48
NFRAMES = 120
FPS = 24


# ============================================================ TEXTURE PAINTING
def to_image(name, c):
    img = bpy.data.images.new(name, c.w, c.h, alpha=True)
    img.pixels.foreach_set(c.to_blender_floats())
    img.update()
    return img


def tex_stone_floor(size=64):
    c = Canvas(size, size)
    base = c.add_colour((92, 90, 102, 255))
    dark = c.add_colour((58, 56, 68, 255))
    light = c.add_colour((126, 124, 138, 255))
    moss = c.add_colour((72, 104, 66, 255))
    L = c.layers[0]
    for p in R.rect(0, 0, size - 1, size - 1, filled=True):
        L.set(*p, base)
    for gy in range(0, size, 16):
        for gx in range(0, size, 16):
            off = 8 if (gy // 16) % 2 else 0
            x0 = (gx + off) % size
            for p in R.rect(x0, gy, min(x0 + 14, size - 1), gy + 14):
                L.set(*p, dark)
            for p in R.line(x0 + 1, gy + 1, min(x0 + 13, size - 2), gy + 1):
                L.set(*p, light)
    for y in range(size):
        for x in range(size):
            if (x * 5 + y * 11) % 19 < 2 and L.get(x, y) == base:
                L.set(x, y, moss)
            elif (x + y) % 2 == 0 and (x * 7 + y * 3) % 23 < 2:
                L.set(x, y, dark)
    return to_image("Tex Stone Floor", c)


def tex_brick_wall(size=64):
    c = Canvas(size, size)
    mortar = c.add_colour((52, 48, 54, 255))
    brick = c.add_colour((124, 76, 66, 255))
    hi = c.add_colour((158, 104, 88, 255))
    lo = c.add_colour((92, 54, 46, 255))
    L = c.layers[0]
    for p in R.rect(0, 0, size - 1, size - 1, filled=True):
        L.set(*p, mortar)
    for i, y in enumerate(range(0, size, 8)):
        off = 0 if i % 2 == 0 else 8
        for x in range(-16 + off, size, 16):
            for p in R.rect(x + 1, y + 1, x + 14, y + 6, filled=True):
                L.set(*p, brick)
    for y in range(size):
        for x in range(size):
            if L.get(x, y) == brick:
                if L.get(x, y - 1) == mortar:
                    L.set(x, y, hi)
                elif L.get(x, y + 1) == mortar:
                    L.set(x, y, lo)
    return to_image("Tex Brick Wall", c)


def tex_wood(size=64):
    c = Canvas(size, size)
    wood = c.add_colour((146, 100, 56, 255))
    seam = c.add_colour((78, 50, 26, 255))
    light = c.add_colour((184, 138, 84, 255))
    iron = c.add_colour((84, 84, 96, 255))
    iron_l = c.add_colour((124, 124, 138, 255))
    L = c.layers[0]
    for p in R.rect(0, 0, size - 1, size - 1, filled=True):
        L.set(*p, wood)
    # five wide planks, each with a dark seam and a lit top edge - at 12 px/unit
    # a plank has to be ~13 texels or it reads as noise on a small crate
    for x in range(0, size, 8):
        for p in R.line(x, 0, x, size - 1):
            L.set(*p, seam)
        for p in R.line(x + 1, 0, x + 1, size - 1):
            L.set(*p, light)
    for y in range(size):                       # grain, along the plank
        for x in range(size):
            if L.get(x, y) == wood and (x * 2 + y * 9) % 31 < 2:
                L.set(x, y, seam)
    for y in (5, size - 9):                    # iron bands across the whole face
        for p in R.rect(0, y, size - 1, y + 4, filled=True):
            L.set(*p, iron)
        for p in R.line(0, y, size - 1, y):
            L.set(*p, iron_l)
    return to_image("Tex Wood", c)


def tex_gold_chest(size=64):
    c = Canvas(size, size)
    wood = c.add_colour((120, 78, 42, 255))
    dark = c.add_colour((70, 44, 22, 255))
    gold = c.add_colour((222, 176, 58, 255))
    L = c.layers[0]
    for p in R.rect(0, 0, size - 1, size - 1, filled=True):
        L.set(*p, wood)
    for x in range(0, size, 9):
        for p in R.line(x, 0, x, size - 1):
            L.set(*p, dark)
    for y in (6, 30, 54):
        for p in R.rect(0, y, size - 1, y + 3, filled=True):
            L.set(*p, gold)
    for p in R.rect(26, 26, 37, 37, filled=True):
        L.set(*p, gold)
    for p in R.rect(30, 30, 33, 35, filled=True):
        L.set(*p, dark)
    return to_image("Tex Chest", c)


# ================================================================ SCENE BUILD
def pixel_mat(name, img, emissive=False):
    """Texture on the object's real UVs.

    NOT Generated coordinates. Generated maps to each object's bounding box, so
    a small crate and a large wall get completely different texel sizes - which
    is the exact defect Texel exists to fix. We unwrap properly and let
    texel.density_apply set one texel size across the whole set.
    """
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nt = mat.node_tree
    bsdf = nt.nodes["Principled BSDF"]
    tex = nt.nodes.new("ShaderNodeTexImage")
    tex.image = img
    tex.interpolation = "Closest"          # texels stay square
    tex.extension = "REPEAT"
    tex.location = (-500, 200)
    mapping = None
    nt.links.new(tex.outputs["Color"], bsdf.inputs["Base Color"])
    bsdf.inputs["Roughness"].default_value = 0.94
    bsdf.inputs["Specular IOR Level"].default_value = 0.08
    if emissive:
        nt.links.new(tex.outputs["Color"], bsdf.inputs["Emission Color"])
        bsdf.inputs["Emission Strength"].default_value = 2.0
    return mat, mapping


def box(name, loc, scale, mat, tile=(1, 1, 1)):
    bpy.ops.mesh.primitive_cube_add(size=1, location=loc)
    o = bpy.context.view_layer.objects.active
    o.name = name
    o.scale = scale
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    bpy.ops.object.shade_flat()
    o.data.materials.append(mat)
    return o


def build():
    bpy.ops.wm.read_factory_settings(use_empty=True)

    floor_img = tex_stone_floor()
    wall_img = tex_brick_wall()
    wood_img = tex_wood()
    chest_img = tex_gold_chest()

    m_floor, map_floor = pixel_mat("Floor", floor_img)
    m_wall, map_wall = pixel_mat("Wall", wall_img)
    m_wood, map_wood = pixel_mat("Wood", wood_img)
    m_chest, _ = pixel_mat("Chest", chest_img)


    box("Floor", (0, 0, -0.2), (16, 16, 0.4), m_floor)
    box("Ceiling", (0, 0, 6.4), (16, 16, 0.4), m_wall)   # kills the sky
    box("WallBack", (0, 7, 3.1), (16, 0.5, 6.6), m_wall)
    box("WallLeft", (-7, 0, 3.1), (0.5, 16, 6.6), m_wall)
    box("WallRight", (7, 0, 3.1), (0.5, 16, 6.6), m_wall)
    for x in (-4.2, 4.2):                                   # pillars
        box(f"Pillar{x}", (x, 4.4, 3.1), (1.0, 1.0, 6.6), m_wall)

    # crates, stacked like a real prop cluster
    for loc, s in (((-3.4, 2.2, 0.55), 1.1), ((-2.4, 2.6, 0.45), 0.9),
                   ((-3.1, 2.5, 1.55), 0.8), ((3.6, 1.4, 0.6), 1.2),
                   ((2.6, 2.4, 0.42), 0.85)):
        o = box("Crate", loc, (s, s, s), m_wood)
        o.rotation_euler = (0, 0, math.radians((loc[0] * 37) % 40 - 20))
    # barrels
    for loc in ((4.6, 3.4, 0.7), (-5.2, 3.8, 0.7)):
        bpy.ops.mesh.primitive_cylinder_add(vertices=10, radius=0.55, depth=1.4,
                                            location=loc)
        o = bpy.context.view_layer.objects.active
        o.name = "Barrel"
        bpy.ops.object.shade_flat()
        o.data.materials.append(m_wood)
    # the chest, lit as the focal point
    box("Chest", (0, 3.4, 0.55), (1.7, 1.1, 1.1), m_chest)

    # torches: emissive quads plus real point lights
    flame = bpy.data.materials.new("Flame")
    flame.use_nodes = True
    fb = flame.node_tree.nodes["Principled BSDF"]
    fb.inputs["Emission Color"].default_value = (1.0, 0.42, 0.10, 1)
    fb.inputs["Emission Strength"].default_value = 5.5
    sconce = bpy.data.materials.new("Sconce")
    sconce.use_nodes = True
    sconce.node_tree.nodes["Principled BSDF"].inputs["Base Color"].default_value = (
        0.05, 0.05, 0.06, 1)
    for x in (-5.9, 5.9):
        box("Bracket", (x, 5.6, 2.2), (0.18, 0.18, 0.9), sconce)
        # a tapered flame: three stacked boxes, smaller as they rise
        for dz, sc in ((0.72, 0.42), (1.02, 0.30), (1.26, 0.17)):
            box("Flame", (x, 5.6, 2.2 + dz), (sc, sc, sc * 1.5), flame)
        li = bpy.data.lights.new("Fire", "POINT")
        li.energy, li.color, li.shadow_soft_size = 900, (1.0, 0.58, 0.26), 0.7
        lo = bpy.data.objects.new("Fire", li)
        bpy.context.collection.objects.link(lo)
        lo.location = (x, 5.3, 3.1)

    key = bpy.data.lights.new("Key", "AREA")
    key.energy, key.size, key.color = 3400, 12, (1.0, 0.9, 0.78)
    ko = bpy.data.objects.new("Key", key)
    bpy.context.collection.objects.link(ko)
    ko.location = (-2, -9, 5.6)
    ko.rotation_euler = (math.radians(38), 0, math.radians(-24))

    world = bpy.data.worlds.new("W")
    world.use_nodes = True
    world.node_tree.nodes["Background"].inputs["Color"].default_value = (
        0.05, 0.06, 0.09, 1)
    world.node_tree.nodes["Background"].inputs["Strength"].default_value = 0.35
    bpy.context.scene.world = world

    # camera on a slow arc, easing in, framing the chest
    cam_d = bpy.data.cameras.new("Cam")
    cam_d.lens = 40
    cam = bpy.data.objects.new("Cam", cam_d)
    bpy.context.collection.objects.link(cam)
    bpy.context.scene.camera = cam
    target = bpy.data.objects.new("Target", None)
    bpy.context.collection.objects.link(target)
    target.location = (0, 2.6, 1.1)
    con = cam.constraints.new("TRACK_TO")
    con.target = target
    con.track_axis, con.up_axis = "TRACK_NEGATIVE_Z", "UP_Y"

    # ---- the part that makes this honest: Texel sets the texel density.
    # Every mesh is cube-unwrapped, then scaled to ONE pixels-per-unit figure,
    # so a crate and a wall show texels of the same physical size.
    sys.path.insert(0, os.path.dirname(HERE))
    import texel as _texel
    try:
        _texel.register()
    except Exception:
        pass
    # Two densities, on purpose. A 1.1 m crate at 12 px/unit only shows 13 of the
    # 64 texels, so the plank seams fall outside the window and the wood reads as
    # noise. Props get 34 px/unit so their detail survives; the floor and walls
    # stay at 12 so their tiles do not turn to mush. This is the density-zone
    # argument, applied for real.
    ARCH = {"Floor", "Ceiling", "WallBack", "WallLeft", "WallRight"}
    done = 0
    for o in [x for x in bpy.data.objects if x.type == "MESH"]:
        base = o.name.split(".")[0]
        arch = base in ARCH or base.startswith("Pillar")
        bpy.context.scene.texel.target_density = 12.0 if arch else 34.0
        bpy.ops.object.select_all(action="DESELECT")
        o.select_set(True)
        bpy.context.view_layer.objects.active = o
        bpy.ops.object.mode_set(mode="EDIT")
        bpy.ops.mesh.select_all(action="SELECT")
        bpy.ops.uv.cube_project(cube_size=1.0)
        bpy.ops.object.mode_set(mode="OBJECT")
        if bpy.ops.texel.density_apply.poll():
            bpy.ops.texel.density_apply()
            done += 1
    bpy.ops.object.select_all(action="DESELECT")
    print(f"[texel] density set on {done} objects: 12 px/unit architecture, "
          f"34 px/unit props", flush=True)
    return cam


def camera_at(cam, t):
    """t in 0..1. A slow arc that pushes in as it swings."""
    e = t * t * (3 - 2 * t)                       # smoothstep, no hard start/stop
    ang = math.radians(-118 + 62 * e)
    rad = 17.0 - 4.6 * e
    cam.location = (math.cos(ang) * rad, math.sin(ang) * rad - 1.0,
                    8.2 - 2.6 * e)


def main():
    t0 = time.perf_counter()
    cam = build()
    sc = bpy.context.scene
    sc.render.engine = "CYCLES"
    try:
        sc.cycles.device = "GPU"
        p = bpy.context.preferences.addons["cycles"].preferences
        p.compute_device_type = "OPTIX"
        p.get_devices()
        for d in p.devices:
            d.use = True
    except Exception as e:
        print(f"[warn] CPU fallback: {e}")
    sc.cycles.samples = SAMPLES
    sc.cycles.use_denoising = True
    sc.render.resolution_x, sc.render.resolution_y = RES
    sc.render.image_settings.file_format = "PNG"
    sc.view_settings.look = "AgX - Medium High Contrast"

    for i in range(NFRAMES):
        camera_at(cam, i / (NFRAMES - 1))
        sc.render.filepath = os.path.join(FRAMES, f"c_{i:04d}")
        bpy.ops.render.render(write_still=True)
        if i % 20 == 0:
            print(f"  frame {i}/{NFRAMES}  {time.perf_counter()-t0:.0f}s", flush=True)

    dst = os.path.join(OUT, "texel-environment.mp4")
    r = subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-framerate", str(FPS),
         "-i", os.path.join(FRAMES, "c_%04d.png"),
         "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "17", dst],
        capture_output=True, text=True)
    ok = r.returncode == 0
    print(f"TEXEL_CINEMATIC_DONE frames={NFRAMES} "
          f"secs={time.perf_counter()-t0:.0f} mp4={'ok' if ok else r.stderr[:120]}",
          flush=True)


if __name__ == "__main__":
    main()
