"""Generate the reference sheet: all 24 ramps, every hex, on one image.

  python funnel/palette_pack/make_sheet.py

This is both the listing's screenshot AND a file in the download, so it is built
the same way as the cover - HTML+CSS through automation/render.mjs, from
facts.json. The debug contact sheet used while choosing the bases was drawn with
PIL, which is banned for anything a customer sees (CLAUDE.md §2); this replaces
it for delivery.

Writes brand/html/texel_palettes_sheet.html.
"""
from __future__ import annotations

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[4]
OUT = ROOT / "brand" / "html" / "texel_palettes_sheet.html"

facts = json.loads((HERE / "facts.json").read_text(encoding="utf8"))
pals, steps, s = facts["palettes"], facts["steps"], facts["summary"]

COLS = 3
per = -(-len(pals) // COLS)          # ceil


def ramp_block(p):
    cells = "".join(f'<i style="background:{c}"></i>' for c in p["colours"])
    ends = f'{p["colours"][0]} &rarr; {p["colours"][-1]}'
    return (f'<div class="p">'
            f'<div class="t"><b>{p["name"]}</b><span>{ends}</span></div>'
            f'<div class="c">{cells}</div></div>')


mid_cells = "".join(
    f'<i style="background:{p["colours"][steps // 2]}" title="{p["name"]}"></i>'
    for p in pals)

columns = ""
for i in range(COLS):
    chunk = pals[i * per:(i + 1) * per]
    columns += '<div class="col">' + "".join(ramp_block(p) for p in chunk) + "</div>"

HTML = f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="_fonts.css">
<style>
  /* Texel Material Palettes - reference sheet, 1600x1000.
     GENERATED by funnel/palette_pack/make_sheet.py from facts.json. Every hex
     printed here is read out of the built .gpl files, so the sheet cannot
     disagree with the download. Edit the generator, not this file.

     Same ember/charcoal family as the covers, but this one is a REFERENCE, not
     a sales image: the job is that someone can read a hex off it, so the type
     is set for legibility at full size rather than for punch at thumbnail. */
  :root {{
    --char:#141317; --char2:#1d1c22; --cream:#f2e6c8;
    --ember:#ff9c3f; --gold:#e7b23a; --quiet:#a89d89; --hero:#fff8ec;
  }}
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ width:1600px; height:1000px; overflow:hidden;
    background:linear-gradient(168deg, var(--char2), var(--char) 72%); }}
  .bar {{ height:64px; background:linear-gradient(90deg, var(--ember), var(--gold));
    display:flex; align-items:center; justify-content:space-between; padding:0 40px;
    font:18px/1 'PlexMonoBold', ui-monospace, monospace; letter-spacing:.14em;
    color:var(--char); text-transform:uppercase; }}
  .wrap {{ display:flex; gap:40px; padding:32px 40px 0; }}
  .col {{ flex:1; display:flex; flex-direction:column; gap:20px; }}
  .p {{ display:flex; flex-direction:column; gap:8px; }}
  .t {{ display:flex; align-items:baseline; justify-content:space-between; }}
  .t b {{ font:20px/1 'YoungSerif', Georgia, serif; color:var(--hero);
    font-weight:400; }}
  .t span {{ font:12px/1 'PlexMono', ui-monospace, monospace; color:var(--quiet);
    letter-spacing:.06em; }}
  .c {{ display:flex; box-shadow:0 4px 14px rgba(0,0,0,.45); }}
  .c i {{ display:block; flex:1; height:44px; }}
  .mid {{ position:absolute; left:40px; right:40px; bottom:88px;
    display:flex; flex-direction:column; gap:8px; }}
  .mid .t b {{ font:16px/1 'PlexMono', ui-monospace, monospace; color:var(--cream);
    letter-spacing:.04em; }}
  .mid .t span {{ font:13px/1 'PlexMono', ui-monospace, monospace; }}
  .mid .c i {{ height:34px; }}
  .foot {{ position:absolute; left:0; right:0; bottom:0; height:56px;
    background:rgba(0,0,0,.42); border-top:1px solid rgba(255,156,63,.28);
    display:flex; align-items:center; justify-content:space-between; padding:0 40px;
    font:14px/1 'PlexMono', ui-monospace, monospace; color:var(--quiet);
    letter-spacing:.1em; text-transform:uppercase; }}
  .foot b {{ color:var(--cream); font-weight:400; }}
</style>
</head>
<body>
  <div class="bar">
    <span>Texel Material Palettes</span>
    <span>{len(pals)} ramps &middot; {steps} steps &middot; CC0</span>
  </div>
  <div class="wrap">{columns}</div>
  <!-- The master sheet gets shown rather than only mentioned: it is a real file
       in the download (_all-midtones.gpl) and the strip is also what fills the
       band above the footer, which read as dead space in the first render. -->
  <div class="mid">
    <div class="t"><b>_all-midtones.gpl</b><span>one mid step from each of the {len(pals)}, for blocking out a scene</span></div>
    <div class="c">{mid_cells}</div>
  </div>
  <div class="foot">
    <span>Pixelkiln</span>
    <span><b>{s['colours_total']}</b> colours &middot; .gpl</span>
    <span>z3er1n.itch.io/texel</span>
  </div>
</body>
</html>
"""

OUT.write_text(HTML, encoding="utf8", newline="\n")
print(f"make_sheet: wrote {OUT}")
print(f"  {len(pals)} ramps in {COLS} columns of {per}")
