"""Write itch_spec.json for the Material Palettes drop, from facts.json.

Every figure in the listing copy is read out of facts.json rather than typed, so
the page cannot claim a ramp count, a colour count or a hue rotation that the
uploaded files do not have. Drop 1's rule, applied again.
"""
from __future__ import annotations

import json
import os
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
facts = json.loads((HERE / "facts.json").read_text(encoding="utf8"))
s, pals = facts["summary"], facts["palettes"]
steps = facts["steps"]

groups: dict[str, list[str]] = {}
for p in pals:
    groups.setdefault(p["group"], []).append(p["name"])

group_lines = "\n".join(f"{g}: " + ", ".join(names) for g, names in groups.items())

desc = f"""A colour ramp is the part of a pixel-art palette that does the actual work: one material, several steps, dark to light. This is {len(pals)} of them, free and public domain.

WHAT YOU GET

{len(pals)} ramps, {steps} steps each, {s['colours_total']} colours in total, as .gpl files - the GIMP palette format, which Texel, Aseprite, Krita and GIMP all read. Plus a {len(pals)}-colour sheet holding one mid step from every ramp, for blocking out a scene before committing to the full ramps.

{group_lines}

HOW THEY WERE MADE

Every ramp is generated by make_ramp(), a function inside Texel, a pixel-art add-on for Blender. It does two things that a plain darken-toward-black ramp does not:

- The hue ROTATES across the ramp instead of staying fixed. Measured across these {len(pals)} palettes, the rotation runs {s['hue_shift_min']:+.1f} to {s['hue_shift_max']:+.1f} degrees from the darkest step to the lightest.
- Saturation peaks in the MIDTONES rather than climbing with brightness.

The build refuses to produce a file if any of that stops holding. Every ramp must be strictly increasing dark-to-light, must carry no duplicate entries, must not crush its darkest step to black or clip its lightest to white, and must show a measurable hue rotation. Every .gpl is written by Texel's own writer and then read back by Texel's own parser, and the colours have to survive that round trip unchanged.

One more check is worth naming, because it is the one that changed the pack. No two palettes' midtones may sit closer than 12 dE76 - roughly the perceptual distance below which two colours stop being two colours. The first draft failed it seven times over: two near-identical greys, two near-identical tans, three barely separable browns. The set was rebuilt around hue coverage instead of around names, and the closest pair is now 14.0 dE.

WHAT THIS PACK DOES NOT CLAIM

The plan was to sell these as "tuned for lit 3D", with a note on why a 3D palette needs more midtones than a 2D one. That note is not here, because the claim was tested twice and neither test supported it.

Pooling every ramp entry across five light levels in linear space and measuring CIELAB distance between neighbouring lit swatches, a 4-step ramp and a 7-step ramp over the same value range gave an identical worst gap, and the number of visible jumps went up rather than down. The opposite story - that a lit renderer supplies the contrast, so a 3D palette wants a narrower albedo span - showed no discrimination either: every span tested kept all of its steps distinct.

So these are good, well-separated material ramps, built by a tool made for pixel art in 3D. Whether they suit lit 3D better than any other good palette is not something we measured, so it is not something we will tell you.

LICENCE

CC0, public domain. Commercial or not, no attribution needed.

Texel itself is a separate paid product and is GPL-3.0-or-later. Nothing in this download is GPL - these are colour values.

No email, no sign-up, no newsletter.

AI DISCLOSURE

Built with AI assistance, like the rest of Pixelkiln's work. The ramps are not a language model's colour opinions - they are Texel's own code, run, and gated.

Made by Pixelkiln. The add-on that generated these ramps, and that paints pixel art straight onto your models in Blender: https://z3er1n.itch.io/texel"""

spec = {
    "title": "Texel Material Palettes",
    "slug": "texel-material-palettes",
    "tagline": (f"Free CC0: {len(pals)} eight-step colour ramps for pixel art, "
                "as .gpl for Texel, Aseprite, Krita and GIMP."),
    "classification": "assets",
    "tags": ["pixel-art", "palette", "color-palette", "blender", "gamedev",
             "textures", "low-poly", "assets"],
    "ai_parts": ["ai_graphics", "ai_code", "ai_text"],
    "files": [(HERE / "texel-material-palettes.zip").as_posix()],
    "cover": (HERE / "cover.png").as_posix(),
    "screenshots": [(HERE / "sheet.png").as_posix()],
    "description": desc,
}

# The one link the whole drop exists to create must be present and must be the
# closing line. Drop 1 shipped a PDF with the URL as plain text and referred
# almost nobody; that is the failure this assert exists to make impossible.
assert desc.rstrip().endswith("https://z3er1n.itch.io/texel"), \
    "the description must END with the Texel link"
assert desc.count("https://z3er1n.itch.io/texel") == 1, \
    "one link, not a pitch"

(HERE / "itch_spec.json").write_text(
    json.dumps(spec, indent=2, ensure_ascii=False), encoding="utf8")
print(f"make_spec: wrote itch_spec.json, description {len(desc)} chars")
print(f"  title {spec['title']!r}  slug {spec['slug']!r}")
print(f"  tags  {', '.join(spec['tags'])}")
print(f"  ai    {', '.join(spec['ai_parts'])}")
