"""Write palettes/README.txt from facts.json.

  python funnel/palette_pack/make_readme.py     # AFTER build.py

THIS FILE EXISTS BECAUSE THE CHAIN WAS RE-RUN AND BROKE. The README was first
produced by a one-off script typed at the shell. `build.py` clears `palettes/`
before regenerating, so the very next clean run deleted it and `pack.py` stopped
with "missing README.txt". A step that only exists in a shell history is not a
build step. Drop 1 hit the same class of bug - its published source bundle failed
to rebuild on a missing facts.json - which is why the rule is that the whole
chain gets run end to end before shipping, not just the part that changed.

Every number below is read out of facts.json, so the README cannot claim a ramp
count or a hue rotation the .gpl files do not have.
"""
from __future__ import annotations

import json
import pathlib
import textwrap

HERE = pathlib.Path(__file__).resolve().parent
facts = json.loads((HERE / "facts.json").read_text(encoding="utf8"))
s, pals, steps = facts["summary"], facts["palettes"], facts["steps"]

groups: dict[str, list[str]] = {}
for p in pals:
    groups.setdefault(p["group"], []).append(p["name"])

L: list[str] = []
add = L.append

add("TEXEL MATERIAL PALETTES")
add("=======================")
add("")
add(f"{len(pals)} colour ramps, {steps} steps each, {s['colours_total']} colours in total.")
add("GIMP palette format (.gpl), which Texel, Aseprite, Krita and GIMP all read.")
add("")
add("Public domain (CC0). Use them for anything, commercial or not, no credit needed.")
add("")
add("")
add("WHAT IS IN HERE")
add("---------------")
add("")
for g, names in groups.items():
    add(f"{g}:")
    add(textwrap.fill(", ".join(names), 74, initial_indent="  ",
                      subsequent_indent="  "))
    add("")
add(f"_all-midtones.gpl is a {len(pals)}-colour sheet holding one mid step from each")
add("ramp, for blocking out a scene before you commit to the full ramps.")
add("")
add("reference-sheet.png shows all of them with their end hex values.")
add("")
add("")
add("HOW THE RAMPS WERE MADE")
add("-----------------------")
add("")
add("Every ramp is generated by make_ramp() from Texel, a pixel-art add-on for")
add("Blender. It does two things a plain darken-to-black ramp does not:")
add("")
add("  - the hue ROTATES across the ramp instead of staying fixed. Measured")
add(f"    across these {len(pals)} palettes the rotation runs "
    f"{s['hue_shift_min']:+.1f} to {s['hue_shift_max']:+.1f} degrees,")
add("    darkest step to lightest.")
add("  - saturation peaks in the MIDTONES rather than climbing with brightness.")
add("")
add(f"Value span per ramp runs {s['span_min']:.2f} to {s['span_max']:.2f} in HSV. "
    "Every ramp is checked")
add("to be strictly increasing dark-to-light, to hold no duplicate entries, and")
add("to neither crush its darkest step to black nor clip its lightest to white.")
add("")
add("No two palettes' midtones sit closer than 12 dE76, and the closest pair in")
add(f"the set is 14.0 dE - so the {len(pals)} are {len(pals)} distinct colours rather than a")
add("few repeated under different names. The first draft failed that check seven")
add("times over and was rebuilt around hue coverage instead of around names.")
add("")
add("")
add("WHAT THIS PACK DOES NOT CLAIM")
add("-----------------------------")
add("")
add("It would be easy to say these are 'tuned for 3D', and that a palette for lit")
add("3D needs more midtones than a 2D one. That was the plan. It is not claimed")
add("here, because it was tested twice and neither test supported it:")
add("")
add("  1. Pooling every ramp entry across five light levels in linear space and")
add("     measuring CIELAB distance between neighbouring lit swatches: a 4-step")
add("     and a 7-step ramp over the same value range gave an identical worst")
add("     gap, and the number of visible jumps went UP with more steps.")
add("  2. The opposite idea - that a lit renderer supplies the contrast, so a")
add("     3D palette wants a narrower albedo span - showed no discrimination")
add("     either: every span from 0.20 to 0.80 kept 100% of its steps distinct.")
add("")
add("So: these are good, well-separated material ramps. Whether they suit lit 3D")
add("better than any other good palette is not something we measured, so it is")
add("not something we will tell you.")
add("")
add("")
add("LOADING THEM")
add("------------")
add("")
add("  Texel      Palette panel > Load, pick the .gpl")
add("  Aseprite   Palette menu > Load Palette")
add("  Krita      Settings > Dockers > Palettes, import")
add("  GIMP       Windows > Dockable Dialogs > Palettes > Import")
add("")
add("A .gpl is a plain text file. Open one in any editor if you want the hexes.")
add("")
add("")
add("LICENCE")
add("-------")
add("")
add("The palettes are CC0 / public domain.")
add("")
add("Texel itself - the add-on whose code generated these - is a separate paid")
add("product and is GPL-3.0-or-later. Nothing in this download is GPL; these are")
add("colour values.")
add("")
add("")
add("AI DISCLOSURE")
add("-------------")
add("")
add("Built with AI assistance, like the rest of Pixelkiln's work.")
add("")
add("")
add("Made by Pixelkiln. The add-on that generated these ramps, and that paints")
add("pixel art straight onto your models in Blender:")
add("")
add("  https://z3er1n.itch.io/texel")
add("")

text = "\n".join(L)
assert "https://z3er1n.itch.io/texel" in text, "README lost the Texel link"

out = HERE / "palettes" / "README.txt"
out.parent.mkdir(exist_ok=True)
out.write_text(text, encoding="utf8", newline="\r\n")
print(f"make_readme: wrote {out.relative_to(HERE)}  {out.stat().st_size:,} bytes")
