"""Generate the nearest-vs-bilinear halving comparison, for real.

The claim this asset carries is that halving an INDEXED sprite by nearest
neighbour keeps every colour inside the palette, and that any interpolating
filter cannot. That is a property of the resampling maths, so the "other side"
is generated by running Pillow's own `Image.BILINEAR` on the same source file -
never mocked up, and never presented as what some other product does.

Source is `original.png`, the same sprite the 0.2.0 transform card uses, which
is itself output from Texel's shipped `core.select.transform_region`.

Writes, beside this file:
    nn_half.png   23x23  nearest-neighbour half
    bl_half.png   23x23  bilinear half
    pal_nn.png    Nx1    the colours present in nn_half, one texel each
    pal_bl.png    Nx1    the colours present in bl_half, one texel each
    resample_facts.json  every number the card is allowed to print

Nothing here prints a number the card does not derive from this file, so the
picture and the caption cannot disagree.
"""

import json
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))


def opaque(img):
    return [p for p in img.get_flattened_data() if p[3] > 0]


def ordered_colours(img):
    """Colours present, most frequent first - a stable order for the strip."""
    counts = {}
    for p in opaque(img):
        counts[p] = counts.get(p, 0) + 1
    return [c for c, _ in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))]


def strip(colours, path):
    im = Image.new("RGBA", (len(colours), 1))
    im.putdata(colours)
    im.save(path)
    return len(colours)


def main():
    src = Image.open(os.path.join(HERE, "original.png")).convert("RGBA")
    palette = set(opaque(src))
    half = (src.width // 2, src.height // 2)

    facts = {
        "source": "original.png",
        "source_size": list(src.size),
        "source_texels": len(opaque(src)),
        "source_colours": len(palette),
        "half_size": list(half),
    }

    for key, filt, name in (
        ("nearest", Image.NEAREST, "nn"),
        ("bilinear", Image.BILINEAR, "bl"),
    ):
        im = src.resize(half, filt)
        im.save(os.path.join(HERE, f"{name}_half.png"))
        cols = ordered_colours(im)
        strip(cols, os.path.join(HERE, f"pal_{name}.png"))
        facts[key] = {
            "texels": len(opaque(im)),
            "colours": len(cols),
            # The load-bearing number: colours the source palette never held.
            "colours_not_in_palette": len([c for c in cols if c not in palette]),
            # The other half of the damage - a sprite's edge stops being a
            # hard edge, which is what breaks it over any background.
            "partial_alpha_texels": len(
                [p for p in im.get_flattened_data() if 0 < p[3] < 255]
            ),
        }

    with open(os.path.join(HERE, "resample_facts.json"), "w", encoding="utf-8") as fh:
        json.dump(facts, fh, indent=2)
    print(json.dumps(facts, indent=2))


if __name__ == "__main__":
    main()
